version: '3'
services:
  your-app:
    image: spring_mvc_selenium_docker
    ports:
      - "8080:8080"
  selenium-hub:
    image: selenium/hub
    ports:
      - "4445:4444"
  selenium-chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
  selenium-firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
